### ISSUE TITLE
Fails to build on GHC 7.8.*

### ISSUE THREAD

**Issue by ygale** [bttr/psqueues#13]
This is an FTP breakage issue. In 0.2.1.0, module Data,OrdPSQ.Internal specifies deriving `Traversable`, but `Traversable` is not in scope. Also, does the `DerivingTraversable` extension even exist in GHC 7.8.*?

**Comment by ygale** [comment]
Yes, according to the [docs for GHC 7.8.4](http://downloads.haskell.org/~ghc/7.8.4/docs/html/users_guide/deriving.html) `DerivingTraversable` is already supported there. So it's only the FTP breakage problem.

**Comment by erikd** [comment]
I'm seeing this with one of my packages as well.

**Comment by jaspervdj** [comment]
Released as `psqueues-0.2.2.0`

**Comment by ygale** [comment]
Thanks @erikd and @jaspervdj !
