### ISSUE TITLE
Test suite requires QuickCheck 2.7

### ISSUE THREAD

**Issue by snoyberg** [bttr/psqueues#2]
QuickCheck-2.8.1 depended on by:
- psqueues-0.2.0.1 (==2.7.*). No maintainer. @bttr

**Comment by jaspervdj** [comment]
Fix uploaded as `psqueues-0.2.0.2`. I've also added myself as Stackage maintainer in a separate PR.

**Comment by snoyberg** [comment]
Thanks!
